### ISSUE TITLE
Concat helper on transition element's class breaks enter transition

### ISSUE THREAD

**Issue by chasegiunta** [miguelcobain/ember-css-transitions#82]
Using `concat` helper on a transition elements `class` attribute breaks enter transition for that element.

eg
```
class={{concat
          this.customClass
          "my-other-classes"
        }}
        {{css-transition
          enterClass="opacity-0"
          enterActiveClass="transition-opacity duration-500 delay-150 ease-out"
          enterToClass="opacity-100"
          leaveClass="opacity-100"
          leaveActiveClass="transition-all duration-500 ease-in"
          leaveToClass="opacity-0"
        }}
        ```

**Comment by SergeAstapov** [comment]
@chasegiunta do you mind to create minimal reproduction via new repository on GitHub?

**Comment by SergeAstapov** [comment]
@chasegiunta thank you for the write up! I assume those plugins do mess with DOM in some way that affects animations...

On the other hand, my personal rule of thumb is to *always* run *any* 3rd party integrations in separate tick to not affect Ember.js rendering process/operation.

I'm not sure there is anything specific about `ember-css-transitions` though.
