### ISSUE TITLE
Changelog entry for v4

### ISSUE THREAD

**Issue by bertdeblock** [miguelcobain/ember-css-transitions#83]
Can't seem to find a changelog entry for v4.
Other than the fact that this is now a v2 addon, are there any other notable changes one should be aware of?

**Comment by SergeAstapov** [comment]
#76, #77, #78, #79 were part of v4 (see [diff](https://github.com/peec/ember-css-transitions/compare/v3.1.0...v4.0.0)) and those PRs lack any label hence changelog was not generated.

@miguelcobain mind to add labels? I can make PR to update changelog then

**Comment by SergeAstapov** [comment]
fixed by #91
