### ISSUE TITLE
`ember-modifier` v3.2 deprecations

### ISSUE THREAD

**Issue by bertdeblock** [miguelcobain/ember-css-transitions#86]
`ember-modifier` v3.2 introduced new deprecations which will also be triggered by the `css-transition` modifier in this addon.
The migration guide can be found [here](https://github.com/ember-modifier/ember-modifier/blob/master/MIGRATIONS.md).

**Comment by SergeAstapov** [comment]
fixed by #87

**Comment by bertdeblock** [comment]
Thanks @SergeAstapov! 👍
